defmodule AshActivityPlanner.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:activity_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text
      add :description, :text
    end

    alter table(:activities) do
      add :activity_group_id,
          references(:activity_groups,
            column: :id,
            name: "activities_activity_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:activities, "activities_activity_group_id_fkey")

    alter table(:activities) do
      remove :activity_group_id
    end

    drop table(:activity_groups)
  end
end
