defmodule AshActivityPlanner.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:participants) do
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:participants) do
      modify :name, :text, null: true
    end
  end
end
