defmodule AshActivityPlanner.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :title, :text
      add :description, :text
      add :start_time, :utc_datetime
      add :end_time, :utc_datetime
    end
  end

  def down do
    drop table(:activities)
  end
end
